### ISSUE TITLE
Can't access the repository

### ISSUE THREAD

**Issue by johnny2k** [joereynolds/reap-get#7]
`urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
`

I followed the trace and found this line in package_repository.py
`    18     def __init__(self, json_path = 'http://reap-get.com/assets/packages.json'): 
`

reap-get.com doesn't resolve to any address so I'm guessing your domain expired.

Would you add the json file to the project? I'll make modifications so that it will fall back on that if the server is unavailable.

**Comment by joereynolds** [comment]
Wow, definitely my bad there. I've added a local copy to the repo under `src/data/`.

You're correct about the domain, it has expired and I've got interest in re-writing it to be open-source when I get the time.

Thanks for the interest!

https://github.com/joereynolds/reap-get/commit/0cf8c85c3f89f935e372a79be3fe2fb3a4823e5b
