### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by hashrock** [joereynolds/reap-get#8]
I think this repo has great idea, It seems be useful for distributing daw's project files.

I think this url is not working, how about using GitHub Pages or Netlify to publish this file:

http://reap-get.com/assets/packages.json

Thanks!

**Comment by joereynolds** [comment]
Hey @hashrock, 

That page died a while ago, I will look into fixing this though.
Thanks for the reminder!

In the meantime, you can change the directory to point to the local `packages.json` file in the `data` directory if you want to see it working

**Comment by hashrock** [comment]
Thank you for reply! I'll try this using local packages.json 👍
